puts "The students of my cohort at Makers Academy"
puts "-----------------------"
puts "Peter Saxton"
puts "Nabin Rai"
puts "Makis Otman"
puts "Mihai-Liviu Cojocar"
puts "Biwek Shrestha"
puts "Audrey Krahmal"
puts "Kalle Malmiharju"
puts "Ayaz Goulamabasse"
puts "Colin Frankish"
puts "Jorja Tracy Hung"
puts "Roy Gardiner"
puts "Abraham Thomas"
puts "James Hunter"
puts "Rolando Barbella"
puts "Megan Folsom"
puts "Berta Gutierrez"
print "Overall, we have"
print "16 "
puts "great students."
